# generated
name: x_dggxbayu2sxyhaq7
on:
  workflow_dispatch: {}
  workflow_call: {}
permissions: {}
jobs:
  x_qcqxkhml5esaqeur:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    outputs:
      x_bj4cc2h2hi3v3fo3: ${{ steps.run.outputs.x_bj4cc2h2hi3v3fo3 }}
      x_gt6catgdgu264g4q: ${{ steps.run.outputs.x_gt6catgdgu264g4q }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_fl3epdaf2q45vy7x
          x_mf4ay2vqxbvdyops: x_bj4cc2h2hi3v3fo3,x_gt6catgdgu264g4q
          x_b4cwt7aitiooxzab: ${{ secrets.x_ofboj5u6qbr5vb5l }}
          x_fev55bhjdkvg76ed: ${{ secrets.x_ok2f34n3k24c673n }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_g57aj5fqylijz7o6:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
    outputs:
      x_my74lebnf7vv4rac: ${{ steps.run.outputs.x_my74lebnf7vv4rac }}
      x_rrqjb35c64aq2o2t: ${{ steps.run.outputs.x_rrqjb35c64aq2o2t }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_fzt52mdralncoyzh
          x_mf4ay2vqxbvdyops: x_my74lebnf7vv4rac,x_rrqjb35c64aq2o2t
          x_7dr47u4eyre7yqoj: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_gt6catgdgu264g4q }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_rece5gd5tnv5pc3o:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
      - x_g57aj5fqylijz7o6
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        x_wzonp37tjw7xpjaf: ${{ fromJSON(needs.x_g57aj5fqylijz7o6.outputs.x_my74lebnf7vv4rac) }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_wvthsqjjr7yxoyu4
          x_mf4ay2vqxbvdyops: ''
          x_3xbawk6wcvfpbekz: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_gt6catgdgu264g4q }}
          x_kuxrzlcos6avsw67: ${{ matrix.x_wzonp37tjw7xpjaf }}
          x_b4cwt7aitiooxzab: ${{ secrets.x_ofboj5u6qbr5vb5l }}
          x_fev55bhjdkvg76ed: ${{ secrets.x_ok2f34n3k24c673n }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_q7yv5gsxib37ypdq: ${{ secrets.x_r3mwtqsc5lebyji5 }}
          x_cvb435nszjmr24vq: ${{ secrets.x_rtelmb72cenkpot5 }}
          x_2tpnbthofyfoql4e: ${{ secrets.x_omuu3prfeflm7xak }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
          x_slyrze45aqtxvphi: ${{ secrets.x_7fex6i66lrc4ouyt }}
          x_4nx3ne6cg7w4ilgq: ${{ secrets.x_ndin2wcqjm5ukajv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_h57j36mcdilva7vj:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
      - x_rece5gd5tnv5pc3o
    if: ${{ always() }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_ccg6kmtzq5sd2eif
          x_mf4ay2vqxbvdyops: ''
          x_tltklujefiqpdjj2: ${{ needs.x_rece5gd5tnv5pc3o.result }}
          x_yva5mlbyudlmwqel: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_gt6catgdgu264g4q }}
          x_b4cwt7aitiooxzab: ${{ secrets.x_ofboj5u6qbr5vb5l }}
          x_fev55bhjdkvg76ed: ${{ secrets.x_ok2f34n3k24c673n }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_q7yv5gsxib37ypdq: ${{ secrets.x_r3mwtqsc5lebyji5 }}
          x_cvb435nszjmr24vq: ${{ secrets.x_rtelmb72cenkpot5 }}
          x_2tpnbthofyfoql4e: ${{ secrets.x_omuu3prfeflm7xak }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
          x_slyrze45aqtxvphi: ${{ secrets.x_7fex6i66lrc4ouyt }}
          x_4nx3ne6cg7w4ilgq: ${{ secrets.x_ndin2wcqjm5ukajv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_ptsxfije3g5pzbp7:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
      - x_g57aj5fqylijz7o6
      - x_h57j36mcdilva7vj
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        x_374zcscjxe2o7csx: ${{ fromJSON(needs.x_g57aj5fqylijz7o6.outputs.x_rrqjb35c64aq2o2t) }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_pxvrbyi36p5dxefb
          x_mf4ay2vqxbvdyops: ''
          x_gprkxyxbp7sbdxxg: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_gt6catgdgu264g4q }}
          x_j7urkf4e55z2zs73: ${{ matrix.x_374zcscjxe2o7csx }}
          x_xw5lpzdq32zv75s5: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_bj4cc2h2hi3v3fo3 }}
          x_b4cwt7aitiooxzab: ${{ secrets.x_ofboj5u6qbr5vb5l }}
          x_fev55bhjdkvg76ed: ${{ secrets.x_ok2f34n3k24c673n }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_q7yv5gsxib37ypdq: ${{ secrets.x_r3mwtqsc5lebyji5 }}
          x_cvb435nszjmr24vq: ${{ secrets.x_rtelmb72cenkpot5 }}
          x_2tpnbthofyfoql4e: ${{ secrets.x_omuu3prfeflm7xak }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
          x_slyrze45aqtxvphi: ${{ secrets.x_7fex6i66lrc4ouyt }}
          x_4nx3ne6cg7w4ilgq: ${{ secrets.x_ndin2wcqjm5ukajv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_rdtcxk3mdlf2xtqs:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
      - x_ptsxfije3g5pzbp7
    if: ${{ always() }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_ksay3usexfgt4s6k
          x_mf4ay2vqxbvdyops: ''
          x_oi5t665kfvliievw: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_bj4cc2h2hi3v3fo3 }}
          x_upzlhdagqva63rkr: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_gt6catgdgu264g4q }}
          x_ve6zvdbvn2mep7p4: ${{ needs.x_ptsxfije3g5pzbp7.result }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
concurrency:
  group: x_dggxbayu2sxyhaq7
  cancel-in-progress: false
