# generated
name: x_dggxbayu2sxyhaq7
on:
  workflow_dispatch: {}
  workflow_call: {}
permissions: {}
jobs:
  x_qcqxkhml5esaqeur:
    name: x_qcqxkhml5esaqeur
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    outputs:
      x_bj4cc2h2hi3v3fo3: ${{ steps.run.outputs.x_bj4cc2h2hi3v3fo3 }}
      x_eqbhleulqok5o5p5: ${{ steps.run.outputs.x_eqbhleulqok5o5p5 }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_fl3epdaf2q45vy7x
          x_mf4ay2vqxbvdyops: x_bj4cc2h2hi3v3fo3,x_eqbhleulqok5o5p5
          x_4dwbpnkawwoiz2ul: ${{ secrets.x_ntcgp3v5p6ixla5l }}
          x_rxbtvkulzhjtavff: ${{ secrets.x_ddqtbewrzlypu474 }}
          x_shs3rk52qvuppzgm: ${{ secrets.x_jfyplpsssgf2hstj }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_g57aj5fqylijz7o6:
    name: x_g57aj5fqylijz7o6
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
    outputs:
      x_v6l7776yaa65qkqa: ${{ steps.run.outputs.x_v6l7776yaa65qkqa }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_fzt52mdralncoyzh
          x_mf4ay2vqxbvdyops: x_v6l7776yaa65qkqa
          x_6k5q5qsihy3niviv: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_eqbhleulqok5o5p5 }}
          x_4dwbpnkawwoiz2ul: ${{ secrets.x_ntcgp3v5p6ixla5l }}
          x_rxbtvkulzhjtavff: ${{ secrets.x_ddqtbewrzlypu474 }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_ptsxfije3g5pzbp7:
    name: x_ptsxfije3g5pzbp7
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
      - x_g57aj5fqylijz7o6
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        x_374zcscjxe2o7csx: ${{ fromJSON(needs.x_g57aj5fqylijz7o6.outputs.x_v6l7776yaa65qkqa) }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_pxvrbyi36p5dxefb
          x_mf4ay2vqxbvdyops: ''
          x_bjerqpcdkiybdj7z: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_eqbhleulqok5o5p5 }}
          x_j7urkf4e55z2zs73: ${{ matrix.x_374zcscjxe2o7csx }}
          x_xw5lpzdq32zv75s5: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_bj4cc2h2hi3v3fo3 }}
          x_4dwbpnkawwoiz2ul: ${{ secrets.x_ntcgp3v5p6ixla5l }}
          x_rxbtvkulzhjtavff: ${{ secrets.x_ddqtbewrzlypu474 }}
          x_shs3rk52qvuppzgm: ${{ secrets.x_jfyplpsssgf2hstj }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
  x_rdtcxk3mdlf2xtqs:
    name: x_rdtcxk3mdlf2xtqs
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_qcqxkhml5esaqeur
      - x_ptsxfije3g5pzbp7
    if: ${{ always() }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_zswwnlosch4hfhvk: ${{ secrets.x_pc4fwbpzwalkmp2w }}
          x_szfclzuqwtjzh7no: ${{ secrets.x_qrzocvnauu6s7nto }}
          x_nsz6yleojteb2p6r: ${{ secrets.x_pd6ix56fdlbbz3a2 }}
          x_viw3fgm7vu23cd3o: x_ksay3usexfgt4s6k
          x_mf4ay2vqxbvdyops: ''
          x_g5pp6papvvmuekgr: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_eqbhleulqok5o5p5 }}
          x_oi5t665kfvliievw: ${{ needs.x_qcqxkhml5esaqeur.outputs.x_bj4cc2h2hi3v3fo3 }}
          x_ve6zvdbvn2mep7p4: ${{ needs.x_ptsxfije3g5pzbp7.result }}
          x_4dwbpnkawwoiz2ul: ${{ secrets.x_ntcgp3v5p6ixla5l }}
          x_rxbtvkulzhjtavff: ${{ secrets.x_ddqtbewrzlypu474 }}
          x_xm6diuhyszbhnck2: ${{ secrets.x_566vfyr4h7egse6x }}
          x_pha7yot3mkhyuvlc: ${{ secrets.x_jahm7rmef2ncek2z }}
          x_ilnlybca5leu73jz: ${{ secrets.x_ajyftwvotnld56zz }}
          x_skarhmkmlfn2z7qx: ${{ secrets.x_b3tyomxfqlbqdkgv }}
        run: ./.github/bin/x_dggxbayu2sxyhaq7
concurrency:
  group: x_dggxbayu2sxyhaq7
  cancel-in-progress: false
